# prefix for tags in git
tagPrefix: v
# defaults are used if they are not overridden by a branch config
defaults {
  tag: false
  tagMessageFormat: "release {Tag}"
  preReleaseFormat: "RC{PreReleaseNumber}"
  buildMetaDataFormat: "{Branch}.{ShortHash}"
  includeBuildMetaData: true
  whenNoValidCommitMessages: IncrementMinor
  patches: [
    PythonSetup
  ]
}
patches: [
  {
    name: PythonSetup
    filePatterns: [
      "VERSION"
    ]
    replacements: [
      {
        find: "{VersionRegex}"
        replace: "{Next}"
      }
    ]
  }
]
