import sys
from pathlib import Path

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib

from .xdg import get_config_dir, get_config_paths

_DEFAULT_CONFIG_CONTENT = """\
# five-clis configuration file
# Generated by: five-clis --init-config
# All keys are optional. Uncomment to activate.

# ----- Display -----

# Terminal colour theme.
# Choices: default, dark, light, mono, rainbow
# Equivalent to: --theme <name>
# theme = "default"

# ----- Seasonal colours -----

# Apply seasonal ANSI colours based on the current date.
# Equivalent to: --seasonal-colours / --no-seasonal-colours
# seasonal-colours = true

# Which cultural calendar drives the seasonal colour scheme.
# Choices: western, jewish, islamic, hindu, sikh, east-asian
# Equivalent to: --seasonal-calendar <name>
# seasonal-calendar = "western"

# ----- Caching -----

# Enable disk caching of API responses.
# Equivalent to: --cache / --no-cache
# cache = false

# How long to cache results. Accepts seconds (300), or suffixed strings (5m, 2h).
# Equivalent to: --cache-ttl <value>
# cache-ttl = "300"

# ----- Updates -----

# Disable the automatic update check.
# Equivalent to: --no-update-check
# no-update-check = false
"""


def load_config(config_path: str | None = None) -> dict:
    """Load TOML config from *config_path* or the standard XDG search paths.

    Returns an empty dict if no config file is found.
    """
    if config_path:
        paths = [Path(config_path)]
    else:
        paths = get_config_paths()

    for path in paths:
        if path.exists():
            try:
                return tomllib.loads(path.read_text(encoding="utf-8"))
            except tomllib.TOMLDecodeError as exc:
                raise ValueError(f"Config parse error in {path}: {exc}") from exc
    return {}


def write_default_config() -> Path:
    """Write the default config to the XDG config directory.

    Returns the path written. Raises ``OSError`` on failure.
    """
    config_dir = get_config_dir()
    config_dir.mkdir(parents=True, exist_ok=True)
    config_path = config_dir / "config.toml"
    if not config_path.exists():
        config_path.write_text(_DEFAULT_CONFIG_CONTENT, encoding="utf-8")
    return config_path


def show_config(cfg: dict, config_path: str | None = None) -> str:
    """Return a human-readable summary of the resolved config."""
    lines = []
    if config_path:
        lines.append(f"Config file: {config_path}")
    else:
        found = next((p for p in get_config_paths() if p.exists()), None)
        lines.append(f"Config file: {found or '(none found)'}")
    lines.append("")
    if cfg:
        for key, value in sorted(cfg.items()):
            lines.append(f"  {key} = {value!r}")
    else:
        lines.append("  (no config keys set)")
    return "\n".join(lines)
